### ISSUE TITLE
Make sure that (on a clean Emacs install) it doesn't trigger LSP

### ISSUE THREAD

**Issue by jaybosamiya** [jaybosamiya/verus-mode.el#1]

**Comment by jaylorch** [comment]
Thanks for the fix! Even with the fix, I still get the LSP error once after I restart emacs, but that's easy to deal with. It's great that it no longer happens every time I open a new Verus file.

**Comment by jaybosamiya** [comment]
Glad the general case is fixed! For the specific once-after-restart case, I haven't really been able to reproduce it.

However, one somewhat hacky way to fix that (which is only ok if you don't plan to use your Emacs instance for any real Rust development, and only for Verus things) is to just globally disable rustic from looking for lsp things. To do that, you could try to update your `.emacs`:
```diff
  (use-package rustic
-   :ensure t)
+   :ensure t
+   :init (setq rustic-lsp-setup-p nil))
```
