### ISSUE TITLE
Use fallback when replacement symbol unavailable

### ISSUE THREAD

**Issue by jaylorch** [jaybosamiya/verus-mode.el#6]
In some fonts, there's no rendering for the symbols used for &&& and |||. It would be good to detect this case and use either a sensible fallback or just forgo the replacement.

**Comment by jaybosamiya** [comment]
I'm not sure if auto-detection is easy but this should be fixable locally for yourself by running `M-x customize-variable RET verus-symbols-alist RET` which will open up a nice interface where you can edit the symbols used for prettification (in particular, you'll be able to remove any prettifications that you do not like by hitting enter on the relevant `[DEL]` or edit it to something your fonts supports---the numbers there correspond to the unicode code point for the prettified character). You can hit `[Apply]` for it to be temporary, or `[Apply and Save]`, to make your changes permanent for your machine.

**Comment by jaylorch** [comment]
This worked, thanks! It would probably be useful to put this in the instructions.
